apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80  # Expose externally on port 80
      targetPort: 9090  # Gateway's internal container port
  type: LoadBalancer  # Exposes the gateway externally
