#version: '3.8'
#
#services:
#  # Eureka Server
#  eureka-server:
#    build: ./eureka
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - bookstore-network
#
#  # API Gateway
#  api-gateway:
#    build: ./gateway
#    container_name: api-gateway
#    ports:
#      - "9090:9090"
#    depends_on:
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#
#  # User Microservice & Database
#  user-db:
#    image: mysql:8.0
#    container_name: user-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: users
#    ports:
#      - "3307:3306"
#    networks:
#      - bookstore-network
#    volumes:
#      - user-data:/var/lib/mysql
#
#  user-service:
#    build: ./user
#    container_name: user-service
#    ports:
#      - "8084:8084"  # ✅ User Microservice exposed on port 8084
#    depends_on:
#      - user-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/users
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # Book Microservice & Database
#  book-db:
#    image: mysql:8.0
#    container_name: book-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: books
#    ports:
#      - "3308:3306"
#    networks:
#      - bookstore-network
#    volumes:
#      - book-data:/var/lib/mysql
#
#  book-service:
#    build: ./book
#    container_name: book-service
#    ports:
#      - "8081:8081"  # ✅ Book Microservice exposed on port 8081
#    depends_on:
#      - book-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/books
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # Cart Microservice & Database
#  cart-db:
#    image: mysql:8.0
#    container_name: cart-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: cart
#    ports:
#      - "3309:3306"
#    networks:
#      - bookstore-network
#    volumes:
#      - cart-data:/var/lib/mysql
#
#  cart-service:
#    build: ./Cart/Cart
#    container_name: cart-service
#    ports:
#      - "8082:8082"  # ✅ Cart Microservice exposed on port 8082
#    depends_on:
#      - cart-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/cart
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # Order Microservice & Database
#  order-db:
#    image: mysql:8.0
#    container_name: order-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: order_db
#    ports:
#      - "3310:3306"
#    networks:
#      - bookstore-network
#    volumes:
#      - order-data:/var/lib/mysql
#
#  order-service:
#    build: ./Order/Order
#    container_name: order-service
#    ports:
#      - "8083:8083"  # ✅ Order Microservice exposed on port 8083
#    depends_on:
#      - order-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/order_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
## Define the network for all services
#networks:
#  bookstore-network:
#    driver: bridge
#
## Define volumes for databases
#volumes:
#  user-data:
#  book-data:
#  cart-data:
#  order-data:

#version: '3.8'
#
#services:
#  # Eureka Server
#  eureka-server:
#    build: ./eureka
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - bookstore-network
#
#  # API Gateway
#  api-gateway:
#    build: ./gateway
#    container_name: api-gateway
#    ports:
#      - "8085:9090"  # External:Internal
#    depends_on:
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#
#  # USER Microservice & Database
#  user-db:
#    image: mysql:8.0
#    container_name: user-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: users
#    ports:
#      - "3307:3306"
#    volumes:
#      - user-data:/var/lib/mysql
#    networks:
#      - bookstore-network
#
#  user-service:
#    build: ./user
#    container_name: user-service
#    ports:
#      - "8084:8080"  # ✅ Expose 8080 inside container, 8084 outside
#    depends_on:
#      - user-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/users
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # BOOK Microservice & Database
#  book-db:
#    image: mysql:8.0
#    container_name: book-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: books
#    ports:
#      - "3308:3306"
#    volumes:
#      - book-data:/var/lib/mysql
#    networks:
#      - bookstore-network
#
#  book-service:
#    build: ./book
#    container_name: book-service
#    ports:
#      - "8081:8080"
#    depends_on:
#      - book-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/books
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # CART Microservice & Database
#  cart-db:
#    image: mysql:8.0
#    container_name: cart-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: cart
#    ports:
#      - "3309:3306"
#    volumes:
#      - cart-data:/var/lib/mysql
#    networks:
#      - bookstore-network
#
#  cart-service:
#    build: ./Cart/Cart
#    container_name: cart-service
#    ports:
#      - "8082:8080"
#    depends_on:
#      - cart-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/cart
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
#  # ORDER Microservice & Database
#  order-db:
#    image: mysql:8.0
#    container_name: order-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: plaksha
#      MYSQL_DATABASE: order_db
#    ports:
#      - "3310:3306"
#    volumes:
#      - order-data:/var/lib/mysql
#    networks:
#      - bookstore-network
#
#  order-service:
#    build: ./Order/Order
#    container_name: order-service
#    ports:
#      - "8083:8080"
#    depends_on:
#      - order-db
#      - eureka-server
#    networks:
#      - bookstore-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/order_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: plaksha
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#
## Networks
#networks:
#  bookstore-network:
#    driver: bridge
#
## Volumes
#volumes:
#  user-data:
#  book-data:
#  cart-data:
#  order-data:

version: '3.8'

networks:
  bookstore-network:

services:
  # Eureka Server
  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bookstore-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  # API Gateway
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    networks:
      - bookstore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # User Microservice & Database
  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plaksha
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    networks:
      - bookstore-network
    volumes:
      - user-data:/var/lib/mysql

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "8084:8084"
    depends_on:
      - user-db
      - eureka-server
    networks:
      - bookstore-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: plaksha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Book Microservice & Database
  book-db:
    image: mysql:8.0
    container_name: book-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plaksha
      MYSQL_DATABASE: books
    ports:
      - "3308:3306"
    networks:
      - bookstore-network
    volumes:
      - book-data:/var/lib/mysql

  book-service:
    build: ./book
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - book-db
      - eureka-server
    networks:
      - bookstore-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/books
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: plaksha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Cart Microservice & Database
  cart-db:
    image: mysql:8.0
    container_name: cart-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plaksha
      MYSQL_DATABASE: cart
    ports:
      - "3309:3306"
    networks:
      - bookstore-network
    volumes:
      - cart-data:/var/lib/mysql

  cart-service:
    build: ./Cart/Cart
    container_name: cart-service
    ports:
      - "8082:8082"
    depends_on:
      - cart-db
      - eureka-server
    networks:
      - bookstore-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/cart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: plaksha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Order Microservice & Database
  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plaksha
      MYSQL_DATABASE: order_db
    ports:
      - "3310:3306"
    networks:
      - bookstore-network
    volumes:
      - order-data:/var/lib/mysql

  order-service:
    build: ./Order/Order
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - order-db
      - eureka-server
    networks:
      - bookstore-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: plaksha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

volumes:
  user-data:
  book-data:
  cart-data:
  order-data:

